# Generated by Django 4.2.13 on 2026-05-13 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
